[tool.poetry]
name = "api"
version = "0.0.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
scikit-learn = "^1.0.2"
numpy = "^1.22.2"
pandas = "^1.4.1"
lightgbm = "^3.3.2"
psycopg2-binary = "^2.9.3"
pydantic = "^1.9.0"
uvicorn = "^0.17.5"
gunicorn = "^20.1.0"
fastapi = "^0.74.0"
redis = "^4.1.4"
cloudpickle = "^2.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
