apiVersion: apps/v1
kind: Deployment
metadata:
  name: similar-image-search-serving
  namespace: search
  labels:
    app: similar-image-search-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: similar-image-search-serving
  template:
    metadata:
      labels:
        app: similar-image-search-serving
    spec:
      initContainers:
        - name: init
          image: shibui/building-ml-system:ai_animals_model_loader_0.0.0
          imagePullPolicy: Always
          command:
            - "python"
            - "-m"
            - "src.main"
          envFrom:
            - configMapRef:
                name: data-paths
          volumeMounts:
            - mountPath: /opt/dataset/data/
              name: data
      containers:
        - name: similar-image-search-serving
          image: shibui/building-ml-system:ai_animals_search_similar_image_search_serving_0.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8500
            - containerPort: 8501
          resources:
            limits:
              cpu: 2000m
              memory: "8000Mi"
            requests:
              cpu: 1000m
              memory: "4000Mi"
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: similar-image-search-serving
  namespace: search
  labels:
    app: similar-image-search-serving
spec:
  ports:
    - name: grpc
      port: 8500
      protocol: TCP
    - name: rest
      port: 8501
      protocol: TCP
  selector:
    app: similar-image-search-serving
