apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: aianimals
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: shibui/building-ml-system:ai_animals_backend_0.0.0
          imagePullPolicy: Always
          command:
            - "./run.sh"
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 500m
              memory: "2000Mi"
            requests:
              cpu: 500m
              memory: "2000Mi"
          env:
            - name: POSTGRES_SERVER
              value: postgres.aianimals.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: aianimals
            - name: RUN_ENVIRONMENT
              value: cloud
            - name: PORT
              value: "8000"
            - name: INITIALIZE
              value: "1"
            - name: DATA_DIRECTORY
              value: /opt/dataset
            - name: WORKERS
              value: "1"
            - name: TIMEOUT
              value: "180"
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: aianimals
  labels:
    app: backend
spec:
  ports:
    - name: backend
      port: 8000
      protocol: TCP
  selector:
    app: backend
