version: "3"

services:
  postgres:
    image: postgres:12.7
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demand_forecasting
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
    hostname: postgres
    restart: always
    stdin_open: true

  db_registration:
    container_name: data_manager
    image: shibui/building-ml-system:demand_forecasting_data_manager_0.0.0
    restart: "no"
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demand_forecasting
    entrypoint:
      - "python"
      - "-m"
      - "src.main"
    volumes:
      - "./data:/opt/data"
    depends_on:
      - postgres
