version: "3"

services:
  postgres:
    image: postgres:12.7
    container_name: postgres
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    networks:
      - default
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demand_forecasting
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
    ports:
      - 5432:5432
    hostname: postgres
    restart: always
    stdin_open: true

  data_manager:
    container_name: data_manager
    image: shibui/building-ml-system:demand_forecasting_data_manager_0.0.0
    restart: always
    networks:
      - default
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demand_forecasting
      - PORT=8000
      - WORKERS=1
    entrypoint:
      - "./run.sh"
    ports:
      - "8000:8000"
    volumes:
      - "./master_data:/opt/data"
    depends_on:
      - postgres

  bi:
    container_name: bi
    image: shibui/building-ml-system:demand_forecasting_bi_0.0.0
    restart: always
    networks:
      - default
    environment:
      - WAIT_SECOND=10
    entrypoint:
      - "streamlit"
      - "run"
      - "src/main.py"
    ports:
      - "8501:8501"
    depends_on:
      - data_manager
networks:
  default:
    name: ml
