apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job
  namespace: default
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: sample-job
          image: ""
          command:
            - "echo"
            - "AAAAAAAAAAAAAAAAAAA"
