apiVersion: batch/v1
kind: Job
metadata:
  name: prefect-job
  namespace: default
  labels:
    identifier: ""
spec:
  template:
    metadata:
      labels:
        identifier: ""
    spec:
      restartPolicy: Never
      containers:
        - name: flow-container
          image: ""
          command: []
          args: []
