apiVersion: apps/v1
kind: Deployment
metadata:
  name: apollo
  namespace: prefect
spec:
  selector:
    matchLabels:
      app: apollo
  template:
    metadata:
      labels:
        app: apollo
    spec:
      containers:
        - name: apollo
          image: prefecthq/apollo:core-0.15.9
          command:
            - "bash"
            - "-c"
          args:
            - "./post-start.sh && npm run serve"
          env:
            - name: GRAPHQL_SERVICE_HOST
              value: "http://graphql.prefect.svc.cluster.local"
            - name: GRAPHQL_SERVICE_PORT
              value: "4201"
            - name: HASURA_API_URL
              value: "http://hasura.prefect.svc.cluster.local:3000/v1alpha1/graphql"
            - name: PREFECT_API_HEALTH_URL
              value: "http://graphql.prefect.svc.cluster.local:4201/health"
            - name: PREFECT_API_URL
              value: "http://graphql.prefect.svc.cluster.local:4201/graphql/"
            - name: PREFECT_SERVER__TELEMETRY__ENABLED
              value: "true"
          ports:
            - containerPort: 4200

---
apiVersion: v1
kind: Service
metadata:
  name: apollo
  namespace: prefect
spec:
  type: ClusterIP
  selector:
    app: apollo
  ports:
    - name: "apollo-port"
      port: 4200
