apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
  namespace: prefect
  labels:
    app: graphql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      labels:
        app: graphql
    spec:
      containers:
        - image: prefecthq/server:core-0.15.9
          name: graphql
          ports:
            - containerPort: 4201
          command:
            - "bash"
            - "-c"
          args:
            - "${PREFECT_SERVER_DB_CMD} && python src/prefect_server/services/graphql/server.py"
          env:
            - name: PREFECT_CORE_VERSION
              value: "0.15.9"
            - name: PREFECT_SERVER_DB_CMD
              value: "prefect-server database upgrade -y"
            - name: PREFECT_SERVER__DATABASE__CONNECTION_URL
              value: "postgresql://prefect:test-password@postgres:5432/prefect_server"
            - name: PREFECT_SERVER__HASURA__ADMIN_SECRET
              value: "hasura-secret-admin-secret"
            - name: PREFECT_SERVER__HASURA__HOST
              value: "hasura"

---
apiVersion: v1
kind: Service
metadata:
  name: graphql
  namespace: prefect
spec:
  type: ClusterIP
  selector:
    app: graphql
  ports:
    - name: "graphql-port"
      port: 4201
