apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: prefect
spec:
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: prefecthq/ui:core-0.15.9
          command:
            - "/intercept.sh"
          env:
            - name: PREFECT_SERVER__APOLLO_URL
              value: "http://apollo.prefect.svc.cluster.local:4200"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: prefect
spec:
  type: ClusterIP
  selector:
    app: ui
  ports:
    - name: "ui-port"
      port: 8080
