apiVersion: v1
kind: Namespace
metadata:
  name: elastic-search
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-search
  namespace: elastic-search
spec:
  version: 7.16.0
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-search
spec:
  version: 7.16.0
  count: 1
  elasticsearchRef:
    name: elastic-search
