apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlflow
  labels:
    app: mlflow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      name: mlflow
      namespace: mlflow
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: shibui/beverage_sales_forecasting_ml_1.0.0
          imagePullPolicy: Always
          command:
            - "mlflow"
            - "server"
            - "--backend-store-uri"
            - "postgresql://postgres:password@postgres.data.svc.cluster.local:5432"
            - "--artifacts-destination"
            - "gs://beverage_sales_forecasting/models"
            - "--serve-artifacts"
            - "--host"
            - "0.0.0.0"
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "2000m"
              memory: "4000Mi"
            requests:
              cpu: "500m"
              memory: "1000Mi"
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlflow
  labels:
    app: mlflow
spec:
  ports:
    - port: 5000
  selector:
    app: mlflow
