apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      name: mlflow
      namespace: mlflow
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: shibui/building-ml-system:beverage_sales_forecasting_mlflow_1.0.0
          imagePullPolicy: Always
          command:
            - "mlflow"
            - "server"
            - "--backend-store-uri"
            - "postgresql://postgres:password@postgres.data.svc.cluster.local:5432"
            - "--default-artifact-root"
            # if you want to store the data into into your storage, instead of `--default-artifact-root`, specify your storage with `--artifacts-destination`.
            # https://www.mlflow.org/docs/latest/tracking.html#artifact-stores
            # E.g.
            # - "--artifacts-destination"
            # - "gs://beverage_sales_forecasting/models"
            - "--serve-artifacts"
            - "--host"
            - "0.0.0.0"
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "2000m"
              memory: "4000Mi"
            requests:
              cpu: "500m"
              memory: "1000Mi"
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlflow
  labels:
    app: mlflow
spec:
  ports:
    - port: 5000
  selector:
    app: mlflow
