apiVersion: apps/v1
kind: Deployment
metadata:
  name: animal-feature-registry
  namespace: aianimals
  labels:
    app: animal-feature-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: animal-feature-registry
  template:
    metadata:
      labels:
        app: animal-feature-registry
    spec:
      containers:
        - name: animal-feature-registry
          image: shibui/building-ml-system:ai_animals_feature_registry_0.0.0
          imagePullPolicy: Always
          command:
            - "python"
            - "-m"
            - "src.main"
            - "--job"
            - "animal_feature_registration_job"
          resources:
            limits:
              cpu: 2000m
              memory: "2000Mi"
            requests:
              cpu: 500m
              memory: "500Mi"
          env:
            - name: POSTGRES_HOST
              value: postgres.data.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: aianimals
            - name: REDIS_HOST
              value: redis.data.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: RABBITMQ_HOST
              value: rabbitmq-amqp.data.svc.cluster.local
            - name: RABBITMQ_USER
              value: user
            - name: RABBITMQ_PASSWORD
              value: password
            - name: RUN_ENVIRONMENT
              value: cloud
            - name: LOG_LEVEL
              value: INFO
            - name: DATA_DIRECTORY
              value: /opt/dataset/data/
            - name: SAVE_DIRECTORY
              value: /tmp/
      imagePullSecrets:
        - name: regcred
