apiVersion: batch/v1
kind: Job
metadata:
  name: initial-data-registry
  namespace: aianimals
  labels:
    app: initial-data-registry
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: init
        image: shibui/building-ml-system:ai_animals_data_registry_0.0.0
        command:
        - "download data"     
        volumeMounts:
        - mountPath: /opt/dataset
          name: dataset
      containers:
      - name: initial-data-registry
        image: shibui/building-ml-system:ai_animals_data_registry_0.0.0
        command:
        - "python"
        - "-m"
        - "src.main"
        - "--job"
        - "initialization_job"
        volumeMounts:
        - mountPath: /opt/dataset
          name: dataset
      volumes:
      - name: dataset
        emptyDir: {}