apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: violation-detection-no-animal-violation-train-
spec:
  entrypoint: violation-detection-no-animal-violation-train
  templates:
    - name: violation-detection-no-animal-violation-train
      container:
        image: shibui/building-ml-system:ai_animals_violation_detection_no_animal_violation_train_0.0.0
        imagePullPolicy: Always
        command:
          - "python"
          - "-m"
          - "src.main"
        env:
          - name: MODEL_CONFIG
            value: mobilenet_v3
          - name: MLFLOW_TRACKING_URI
            value: http://mlflow.mlflow.svc.cluster.local:5000
          - name: MLFLOW_EXPERIMENT
            value: violation_detection_no_animal_violation_detection
        resources:
          requests:
            memory: 12000Mi
            cpu: 2000m
  imagePullSecrets:
    - name: regcred
