apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  generateName: search-similar-image-search-pipeline-
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: "Allow"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: pipeline
    templates:
      - name: pipeline
        steps:
          - - name: search-similar-image-search-train
              template: search-similar-image-search-train
          - - name: print-message
              template: print-message
              arguments:
                parameters:
                  - name: experiment_run
                    value: "{{steps.search-similar-image-search-train.outputs.parameters.experiment_run}}"

      - name: search-similar-image-search-train
        container:
          image: shibui/building-ml-system:ai_animals_search_similar_image_search_train_0.0.0
          imagePullPolicy: Always
          command:
            - "python"
            - "-m"
            - "src.main"
          env:
            - name: MODEL_CONFIG
              value: mobilenet_v3_scann
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow.mlflow.svc.cluster.local:5000
            - name: MLFLOW_EXPERIMENT
              value: search_similar_image_search
            - name: POSTGRES_HOST
              value: postgres.data.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: aianimals
          resources:
            requests:
              memory: 16000Mi
              cpu: 2000m
        outputs:
          parameters:
            - name: experiment_run
              valueFrom:
                path: /tmp/output.json

      - name: print-message
        inputs:
          parameters:
            - name: experiment_run
        container:
          image: docker/whalesay:latest
          command: [cowsay]
          args: ["{{inputs.parameters.experiment_run}}"]

    imagePullSecrets:
      - name: regcred
