apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: search-similar-image-search-train-
spec:
  entrypoint: search-similar-image-search-train
  templates:
    - name: search-similar-image-search-train
      container:
        image: shibui/building-ml-system:ai_animals_search_similar_image_search_train_0.0.0
        imagePullPolicy: Always
        command:
          - "python"
          - "-m"
          - "src.main"
        env:
          - name: MODEL_CONFIG
            value: mobilenet_v3_scann
          - name: MLFLOW_TRACKING_URI
            value: http://mlflow.mlflow.svc.cluster.local:5000
          - name: MLFLOW_EXPERIMENT
            value: search_similar_image_search
        resources:
          requests:
            memory: 8000Mi
            cpu: 2000m
  imagePullSecrets:
    - name: regcred
