name: beverage_sales_forecasting
jobs:
  data:
    source: local
    path: /opt/data/data/item_sales_records_train_2021_03.csv
    target_data:
      date_from: 2017-01-01
      date_to: 2021-01-11
      item: ALL
      store: ALL
      region: ALL
    train:
      year: 2017
      week: 1
    test:
      year: 2021
      week: 1
    predict:
      year: 2021
      week: 3
      items: ALL
      stores: ALL

  model:
    name: light_gbm_regression
    params:
      task: "train"
      boosting: "gbdt"
      objective: "regression"
      num_leaves: 3
      learning_rate: 0.05
      feature_fraction: 0.5
      max_depth: -1
      num_iterations: 1000000
      num_threads: 0
      seed: 1234
      early_stopping_rounds: 200
      eval_metrics: mse
      verbose_eval: 1000

  optimize:
    run: false
    optuna:
      n_trials: 100
      n_jobs: 1
      metrics: mean_absolute_error
      light_gbm:
        parameters:
          - name: num_leaves
            suggest_type: int
            value_range:
              - 2
              - 10
          - name: learning_rate
            suggest_type: uniform
            value_range:
              - 0.01
              - 0.1
          - name: feature_fraction
            suggest_type: uniform
            value_range:
              - 0.1
              - 1.0

  train:
    run: true

  predict:
    run: true
    register: true
