version: "3"

services:
  postgres:
    image: postgres:13.5
    container_name: postgres
    restart: always
    networks:
      - default
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=aianimals
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
    hostname: postgres
    stdin_open: true

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    networks:
      - default
    ports:
      - 6379:6379
    hostname: redis

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    networks:
      - default
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    hostname: rabbitmq

  initial_data_registry:
    container_name: initial_data_registry
    image: shibui/building-ml-system:ai_animals_data_registry_0.0.0
    volumes:
      - ./dataset/:/opt/dataset/
    restart: "no"
    networks:
      - default
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=aianimals
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=user
      - RABBITMQ_PASSWORD=password
      - ES_HOST=es
      - ES_SCHEMA=http
      - ES_PORT=9200
      - LOG_LEVEL=INFO
      - RUN_ENVIRONMENT=local
      - DATA_DIRECTORY=/opt/dataset
    command: >
      /bin/sh -c "sleep 20s && python -m src.main --job initialization_job"
    depends_on:
      - postgres
      - redis

  api:
    container_name: api
    image: shibui/building-ml-system:ai_animals_api_0.0.0
    volumes:
      - ./api/secrets/secret.key:/opt/secrets/secret.key
    restart: always
    networks:
      - default
    ports:
      - 8000:8000
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=aianimals
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=user
      - RABBITMQ_PASSWORD=password
      - ANIMAL_REGISTRY_QUEUE=animal
      - NO_ANIMAL_VIOLATION_QUEUE=no_animal_violation
      - LOG_LEVEL=INFO
      - RUN_ENVIRONMENT=local
      - DATA_DIRECTORY=/opt/dataset
      - KEY_FILE_PATH=/opt/secrets/secret.key
      - WORKERS=1
      - INITIALIZE=1
      - PORT=8000
    command: ./run.sh
    hostname: api
    depends_on:
      - postgres
      - redis
      - rabbitmq

  es:
    container_name: es
    image: shibui/building-ml-system:ai_animals_elasticsearch_0.0.0
    volumes:
      - ./infrastructure/local_conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    restart: always
    networks:
      - default
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9201:9201
      - 127.0.0.1:9300:9300
    environment:
      - discovery.type=single-node
    hostname: es
    depends_on:
      - postgres

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.16.0
    restart: always
    networks:
      - default
    ports:
      - 127.0.0.1:5601:5601
    environment:
      - ELASTICSEARCH_HOSTS="http://es:9200"
    hostname: kibana
    depends_on:
      - postgres

  search_registry:
    container_name: search_registry
    image: shibui/building-ml-system:ai_animals_data_registry_0.0.0
    restart: always
    networks:
      - default
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=aianimals
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=user
      - RABBITMQ_PASSWORD=password
      - ES_HOST=es
      - ES_SCHEMA=http
      - ES_PORT=9200
      - LOG_LEVEL=INFO
      - RUN_ENVIRONMENT=local
      - DATA_DIRECTORY=/opt/dataset
    command: >
      /bin/sh -c "sleep 20s && python -m src.main --job animal_to_search_job"
    depends_on:
      - postgres
      - redis
      - api
      - es

  no_animal_violation:
    container_name: no_animal_violation
    image: shibui/building-ml-system:ai_animals_violation_detection_no_animal_violation_0.0.0
    restart: always
    networks:
      - default
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=aianimals
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=user
      - RABBITMQ_PASSWORD=password
      - CONSUMING_QUEUE=no_animal_violation
      - REGISTRATION_QUEUE=violation
    command: >
      /bin/sh -c "sleep 20s && python -m src.main"
    depends_on:
      - postgres
      - rabbitmq
      - initial_data_registry

  violation_registry:
    container_name: violation_registry
    image: shibui/building-ml-system:ai_animals_violation_detection_registry_0.0.0
    restart: always
    networks:
      - default
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=aianimals
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=user
      - RABBITMQ_PASSWORD=password
      - VIOLATION_QUEUE=violation
    command: >
      /bin/sh -c "sleep 20s && python -m src.main"
    depends_on:
      - postgres
      - rabbitmq
      - initial_data_registry

networks:
  default:
    name: aianimals
