version: "3"

services:
  postgres:
    image: postgres:13.5
    container_name: postgres
    restart: always
    networks:
      - default
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=aianimals
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
    hostname: postgres
    stdin_open: true

  backend:
    container_name: backend
    image: shibui/building-ml-system:ai_animals_backend_0.0.0
    restart: always
    networks:
      - default
    ports:
      - 8000:8000
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=aianimals
      - LOG_LEVEL=INFO
      - RUN_ENVIRONMENT=local
      - DATA_DIRECTORY=/opt/dataset
      - WORKERS=1
      - INITIALIZE=1
      - PORT=8000
    command: ./run.sh
    depends_on:
      - postgres

networks:
  default:
    name: aianimals
