version: "3"

services:
  postgres:
    image: postgres:13.5
    container_name: postgres
    restart: always
    networks:
      - default
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=aianimals
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
    hostname: postgres
    stdin_open: true

  data_manager:
    container_name: data_manager
    image: shibui/building-ml-system:ai_animals_data_manager_0.0.0
    restart: "no"
    networks:
      - default
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=aianimals
      - LOG_LEVEL=DEBUG
      - RUN_ENVIRONMENT=local
      - DATA_DIRECTORY=/opt/dataset
    command: >
      /bin/sh -c "sleep 5s && python -m src.main"
    depends_on:
      - postgres

  backend:
    container_name: backend
    image: shibui/building-ml-system:ai_animals_backend_0.0.0
    restart: always
    networks:
      - default
    ports:
      - 8000:8000
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=aianimals
      - LOG_LEVEL=INFO
      - RUN_ENVIRONMENT=local
      - DATA_DIRECTORY=/opt/dataset
      - WORKERS=1
      - INITIALIZE=1
      - PORT=8000
    command: ./run.sh
    hostname: backend
    depends_on:
      - postgres

  es:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.0
    volumes:
      - ./local_conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    restart: always
    networks:
      - default
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9201:9201
      - 127.0.0.1:9300:9300
    environment:
      - discovery.type=single-node
    hostname: es
    depends_on:
      - postgres

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.16.0
    restart: always
    networks:
      - default
    ports:
      - 127.0.0.1:5601:5601
    environment:
      - ELASTICSEARCH_HOSTS="http://es:9200"
    hostname: kibana
    depends_on:
      - postgres

networks:
  default:
    name: aianimals
