name: chapter3_4_aianimals

on:
  push:
    branches:
      - test/*
      - build/*
      - all/*
      - develop
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push api image
        working-directory: ./chapter3_4_aianimals
        env:
          DOCKER_BUILDKIT: 1
        run: |
          build_data_registry
          build_api
          build_ab_test_proxy
          build_es
          build_violation_detection_no_animal_violation_proxy
          build_violation_detection_registry
          build_violation_detection_no_animal_violation_train
          build_search_learn_to_rank_train
          push_api
          push_ab_test_proxy
          push_data_registry
          push_es
          push_violation_detection_no_animal_violation_proxy
          push_violation_detection_no_animal_violation_serving
          push_violation_detection_registry
          push_violation_detection_no_animal_violation_train
          push_search_learn_to_rank_train
